### ISSUE TITLE
Image urls not working  selected_images.csv

### ISSUE THREAD

**Issue by m-bain** [mjskay/gender-in-image-search#1]
Hi I was wondering if its possible to get a mirror for the images in selected_images.csv because the urls are no longer working.

Quite an urgent request because we have to respond to reviews this week and evaluate on this dataset - thanks!
http://homes.cs.washington.edu/~mjskay/aws-images/google/chief executive officer/5.jpg

**Comment by mjskay** [comment]
Ah yeah, sorry since I've moved institutions those aren't working anymore. short term if you send me an email (at mjskay@northwestern.edu) I can send you the image archive.

**Comment by m-bain** [comment]
Thanks, will send an email :)

**Comment by timqqt** [comment]
Could you please share the image archive somewhere in this page? It is easy for people to get using your dataset. Thank you!

**Comment by mjskay** [comment]
Sure, I added a note with a link here: https://github.com/mjskay/gender-in-image-search/blob/master/data/public/README.md

**Comment by timqqt** [comment]
> Sure, I added a note with a link here: https://github.com/mjskay/gender-in-image-search/blob/master/data/public/README.md

Thank you very much for your kindly help!
